# name: Manual Push to Another Repository

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   push:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Source Repository
#       uses: actions/checkout@v2
#       with:
#         token: ${{ secrets.GH_PAT }}
#         ref: 'develop'

#     - name: Setup Git Config
#       run: |
#         git config --global user.name 'GitHub Action'
#         git config --global user.email 'action@github.com'

#     - name: Push to Target Repository
#       run: |
#         run: git remote add target https://oauth2:${{ secrets.DEV_TARGET_GH_TOKEN }}@github.com/${{ secrets.DEV_TARGET_GH_USERNAME }}/SnowbirdsAI.git
#         git push target HEAD:develop

name: Develop Workflow

on:
  push:
    branches:
      - develop

env:
  REPOSITORY_NAME: SnowbirdsAI.git
  TARGET_GH_USERNAME: ${{ secrets.DEV_TARGET_GH_USERNAME }}
  TARGET_GH_TOKEN: ${{ secrets.DEV_TARGET_GH_TOKEN }}
  
jobs:
  Deploy-develop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Add target GitHub remote
      run: |
        git remote add target https://oauth2:${{ env.TARGET_GH_TOKEN }}@github.com/${{ env.TARGET_GH_USERNAME }}/${{ env.REPOSITORY_NAME }}
    

    - name: Set up Git credentials
      run: |
        git config --global credential.helper store
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git credential approve <<< "url=https://github.com/
          username=${{ env.TARGET_GH_USERNAME }}
          password=${{ env.TARGET_GH_TOKEN }}"


    - name: Push develop to the develop branch
      run: |
        # Force push the changes from the develop branch to the develop branch on target GitHub Repository
        git push target develop:develop --force