name: Develop Workflow

on:
  push:
    branches:
      - develop

env:
  REPOSITORY_NAME: SnowbirdsAI
  TARGET_GH_USERNAME: ${{ secrets.DEV_TARGET_GH_USERNAME }}
  TARGET_GH_TOKEN: ${{ secrets.DEV_TARGET_GH_TOKEN }}
  
jobs:
  Deploy-develop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      # Using a token specific to the operation, ensuring it has the minimum required permissions.
      with:
        token: ${{ secrets.GH_PAT }}
        
    # The 'git remote add' command allows the addition of a new remote end-point to the local repo.
    - name: Add target GitHub remote
      run: |
        git remote add origin_remote_dev https://oauth2:${{ env.TARGET_GH_TOKEN }}@github.com/${{ env.TARGET_GH_USERNAME }}/${{ env.REPOSITORY_NAME }}.git

    # Setting up Git credentials globally can be avoided, but it's here for custom user configurations.
    - name: Set up Git credentials
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    # Pushing changes to the remote branch with error handling.
    - name: Push develop to the develop branch
      run: |
        set -e  # Any command which returns non-zero exit code will cause this shell script to exit immediately
        # Checking out the develop branch, this step may be redundant but is kept for clarity.
        git checkout develop
        # Push changes, avoiding force push for safety.
        git push origin_remote_dev develop:develop