name: Develop Workflow

on:
  push:
    branches:
      - release

env:
  REPOSITORY_NAME: SnowbirdsAI.git
  TARGET_GH_USERNAME: ${{ secrets.QA_TARGET_GH_USERNAME }}
  TARGET_GH_TOKEN: ${{ secrets.QA_TARGET_GH_TOKEN }}
  
jobs:
  Deploy-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Add target GitHub remote
      run: |
        git remote add target https://oauth2:${{ env.TARGET_GH_TOKEN }}@github.com/${{ env.TARGET_GH_USERNAME }}/${{ env.REPOSITORY_NAME }}
    
    - name: Set up Git credentials
      run: |
        git config --global credential.helper store
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git credential approve <<< "url=https://github.com/
          username=${{ env.TARGET_GH_USERNAME }}
          password=${{ env.TARGET_GH_TOKEN }}"

    - name: Push release to the release branch
      run: |
        # Force push the changes from the release branch to the release branch on target GitHub Repository
        git push target release:release --force